---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Práctica de campo

>Los viajes de campo nos ayudan a ratificar que sabemos poco o nada acerca de la naturaleza

No deberían existir obstáculos para salir al campo porque, a fin de cuentas, es allí donde podemos recoger datos y donde nos surgirán nuevas preguntas. Normalmente, durante una fase de exploración, los planes son inútiles, incluso molestos. Pero cuando se trata de responder preguntas concretas, entonces hay que añadir una capa de planificación, que incluya preguntas de investigación y diseño de muestreo, preferiblemente con un enfoque de reproducibilidad (ejem, luego los administrativos te dirán que es más importante hacer 20 solicitudes de cheques, escribir 30 oficios y 10 informes, buscar 50 cotizaciones y cualquier otra vaina con tal de que no viajes; corre por tu vida en el momento que veas más papeles que datos). Este repo aspira a cumplir dicha misión de asesorarte con un mínimo de planificación en tu recogida de datos, reconociendo en todo caso que se trata de un "trabajo en desarrollo".

## Enfoques

Basado en las preguntas de cada estudiante, se puede asumir que hay al menos dos enfoques en los estudios sobre hormigas a realizar:

### Relación con el hábitat

### Nidos

### ¿Acaso hay un tercer enfoque relacionado con cebos?

Parecería que surje un tercero, que es el tema del efecto que pueden tener los cebos en las muestras. Sin embargo, no encontré mucha "fuerza"" en las preguntas formuladas sobre este tema, y pienso que se pueden agrupar en el enfoque "relación con el hábitat".

Utiliza las siguientes listas de control en forma de tareas, para confirmar que dispones de lo necesario para iniciar la colecta de especímenes/datos.

Las parcelas asignadas a cada persona las he obtenido ejecutando el siguiente código. En la tabla de la [tarea 2](#Tarea-2.-Tus-preguntas-de-investigación-y-tus-lugares-de-muestreo), verás cu


## Tarea 1. Estudia el siguiente protocolo de recogida de datos según sea tu caso.

### Relación con hábitat

### Nidos


## Tarea 2. Tus preguntas de investigación y tus lugares de muestreo

Seguramente las tienes a mano, pero te dejo a continuación las URL de los repos con sus preguntas de investigación. Toma nota también de tus lugares de muestreo asignados.

* 
* 
* 

## Tarea 3. Tu formulario de campo

### Formulario de campo para relación con hábitat (A)

### Formulario de campo para estudio de nidos (B)

## Tarea 4. Revisa tu material de campo

* Frascos, mínimo 10, pero dependerá mucho de tus preguntas de investigación.
* Alcohol etílico al 70-80%
* Pincel
* Cebo (variará según tu pregunta de investigación)
* Dispositivo Android + ODK Collect + Formularios descargado). Alternativamente, formularios en papel


## Tarea final. Ajusta tus expectativas

Es probable que, aun teniendo unas preguntas de investigación debidamente formuladas y un diseño de muestreo acorde a lo que quieres responder, te encuentres al final de los análisis con lo que a veces se denomina resultados negativos. Significa que podrías no encontrar un efecto, un patrón, y lo importante es que debes interpretarlo adecuadamente. Considera lo siguiente:

* En primer lugar, considera que tu muestra es pequeña. La idea no es que hagas un completo estudio sobre hormigas, sino que ensayes técnicas de formulación de preguntas, y de recogida y análisis de datos, pensando en aplicarlo a algo más grande en el futuro. Tu tesis será un buen terreno para poner en práctica estas técnicas.

* En segundo lugar, con independencia de que la muestra será pequeña, un resultado negativo es también un resultado, porque responde a unas preguntas y probablemente abre otras.

* Finalmente, reconoce la limitación temporal. En 5 meses no podrás ver ni aplicar todas las técnicas biogeográficas que existen en el "mercado". Sin embargo, dispondrás de fuentes bibliográficas, nuevos recursos y nuevas herramientas para localizar soluciones a tus futuros problemas en ecología.
